using System;
using System.Collections.Generic;

namespace FSI.ClientMgmtTool.Backend.Foundation.DatabaseContext.Entities
{
    public partial class ControlPr
    {
        public int CompanyNo { get; set; }
        public string UpdateJc { get; set; }
        public string UpdateJobToGl { get; set; }
        public string FringeCostClassNo { get; set; }
        public string FicaCostClassNo { get; set; }
        public string MiscDeductionCycle { get; set; }
        public string UnionDeductionCycle { get; set; }
        public string JcEarnCode { get; set; }
        public string JcTradeLab { get; set; }
        public string GlHisFlag { get; set; }
        public string FringeCostCode { get; set; }
        public string FicaCostCode { get; set; }
        public string EmpDetailLabor { get; set; }
        public string EmpDetailBurden { get; set; }
        public string EmpDetailFica { get; set; }
        public string EmpDetailFringe { get; set; }
        public string JcTradeBurden { get; set; }
        public string JcTradeFica { get; set; }
        public string JcTradeFringe { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string ControlDateFlag { get; set; }
        public string LowCheckWarning { get; set; }
        public string P401kDeductionNo { get; set; }
        public decimal? NumberLeadingVoids { get; set; }
        public string DefaultEarnType { get; set; }
        public string ProratePremium { get; set; }
        public string CheckRegSumJob { get; set; }
        public string CheckRegSumAcct { get; set; }
        public string GenTaxGroup { get; set; }
        public string CheckFormat { get; set; }
        public decimal? GlState { get; set; }
        public decimal? GlLocal { get; set; }
        public string DeptPriority { get; set; }
        public string WorkersCompActive { get; set; }
        public decimal? OtDayLimit { get; set; }
        public decimal? OtWeekLimit { get; set; }
        public string OtEarnTypeNo { get; set; }
        public string KeepTimeCardHis { get; set; }
        public string RequireEmpTrade { get; set; }
        public string RequireEmpDept { get; set; }
        public string RequireEmpTaxGroup { get; set; }
        public string RequireEmpWcState { get; set; }
        public string RequireTaxGroup { get; set; }
        public string RequireLocalCounty { get; set; }
        public string HoldVoidFlag { get; set; }
        public string HoldPayoffFlag { get; set; }
        public string SecureEmpToJc { get; set; }
        public string OvhdJobToJc { get; set; }
        public string DefaultSeqLocal { get; set; }
        public string DefaultSeqDiv { get; set; }
        public string DefaultSeqWcState { get; set; }
        public string DefaultSeqWcClass { get; set; }
        public string DefaultSeqUnion { get; set; }
        public string DefaultSeqRate { get; set; }
        public string OtProrate { get; set; }
        public string ShowCheckYtd { get; set; }
        public string ShowPayRate { get; set; }
        public string ShowWords { get; set; }
        public string ShowPayEnding { get; set; }
        public string ShowSummarizedLocal { get; set; }
        public string ShowEmployeeNo { get; set; }
        public string ShowEmpFringes { get; set; }
        public string ShowEmpSs { get; set; }
        public string ShowFringeOnStub { get; set; }
        public string SalAdjEarnTypeNo { get; set; }
        public string SalaryProrate { get; set; }
        public string SalRegEarnTypeNo { get; set; }
        public string ShowTotalScreen { get; set; }
        public string VerifyUnionTrade { get; set; }
        public string SuppressLastJob { get; set; }
        public string UseHighestRate { get; set; }
        public string TimeByDate { get; set; }
        public string EquipUsageToGl { get; set; }
        public string UpdateMinorityCompliance { get; set; }
        public string EnableFullScreen { get; set; }
        public string SortChecks { get; set; }
        public string CheckPrintType { get; set; }
        public string ReprintStub { get; set; }
        public string PayRateScreen2 { get; set; }
        public string EqpDivExp { get; set; }
        public string EqpDivCr { get; set; }
        public string P401kCostCodeNo { get; set; }
        public string P401kCostClassNo { get; set; }
        public string CountyToCertified { get; set; }
        public string DirectDepoistDefault { get; set; }
        public string UseDateConvert { get; set; }
        public string EqpRepairClass1 { get; set; }
        public string EqpRepairClass2 { get; set; }
        public string EqpRepairClass3 { get; set; }
        public string EqpRepairDept1 { get; set; }
        public string EqpRepairDept2 { get; set; }
        public string EqpRepairDept3 { get; set; }
        public string EqpRepairCc1 { get; set; }
        public string EqpRepairCc2 { get; set; }
        public string EqpRepairCc3 { get; set; }
        public string OtEarnTypesApplied1 { get; set; }
        public string OtEarnTypesApplied2 { get; set; }
        public string OtEarnTypesApplied3 { get; set; }
        public string OtEarnTypesApplied4 { get; set; }
        public string OtEarnTypesApplied5 { get; set; }
        public string W2UnionPension1 { get; set; }
        public string W2UnionPension2 { get; set; }
        public string W2UnionPension3 { get; set; }
        public string W2UnionPension4 { get; set; }
        public string W2UnionPension5 { get; set; }
        public string UseCodeRates { get; set; }
        public string TermEmp { get; set; }
        public string CheckStubFormat { get; set; }
        public string SummarizeEmpTc7 { get; set; }
        public string TaxableWording { get; set; }
        public string FringeYtd { get; set; }
        public string ShowRedtPremHours { get; set; }
        public string DuplicateSsFlag { get; set; }
        public string VerifyUnionExpDate { get; set; }
        public int? DefaultDiv1 { get; set; }
        public int? DefaultDiv2 { get; set; }
        public int? DefaultDiv3 { get; set; }
        public int? DefaultDiv4 { get; set; }
        public string NextEmployeeNo { get; set; }
        public string RecordStatus { get; set; }
        public string RowModifiedBy { get; set; }
        public DateTime? RowModifiedOn { get; set; }
        public int RowUniqueId { get; set; }
        public string ShiftNo { get; set; }
        public string DefaultSeqCounty { get; set; }
        public string UseWeekendDate { get; set; }
        public string ShowTaxableEarnings { get; set; }
        public string OtEarnTypeNoRedundant { get; set; }
        public string VerifySplitHours { get; set; }
        public DateTime? UnionLimitStDate { get; set; }
        public DateTime? UnionLimitEnDate { get; set; }
        public string EnableUnionLimitPrd { get; set; }
        public string CompanyId { get; set; }
        public string FicaCostClassId { get; set; }
        public string FringeCostClassId { get; set; }
        public string NextEmployeeId { get; set; }
        public string OtEarnTypeId { get; set; }
        public string P401kCostClassId { get; set; }
        public string P401kCostCodeId { get; set; }
        public string P401kDeductionId { get; set; }
        public string SalAdjEarnTypeId { get; set; }
        public string SalRegEarnTypeId { get; set; }
        public string ShiftId { get; set; }
        public string ShowEmployeeId { get; set; }
        public string WtAvgOtEarnTypeNo { get; set; }
        public string WarnNegativeAccrual { get; set; }
        public string WarnExpiredAccrual { get; set; }
        public string AccrualOnStub { get; set; }
        public string MultiState401Method { get; set; }
        public string DefaultHourlyBenefitTypeNo { get; set; }
        public string DefaultPerPayBenefitTypeNo { get; set; }
        public string DefaultHourlyBenefitTypeId { get; set; }
        public string DefaultPerPayBenefitTypeId { get; set; }
        public string WtAvgOtEarnTypeId { get; set; }
        public string ComputeAccrualDate { get; set; }
        public string OpenAccrualLogAddMode { get; set; }
        public string PrintTaxDepositSummary { get; set; }
        public string CheckPrintFont { get; set; }
        public string EmpFringeGlSource { get; set; }
        public string ShowDeptNo { get; set; }
        public string JcDeptLab { get; set; }
        public string JcDeptBurden { get; set; }
        public string JcDeptFica { get; set; }
        public string JcDeptFringe { get; set; }
        public string ShowDeptId { get; set; }
        public string UseWeekendDateEq { get; set; }
        public string VerifyResidenceAddOn { get; set; }
        public string AllowMultipleChecks { get; set; }
        public string Show401kOnStub { get; set; }
        public string RequireEmpDateHired { get; set; }
        public string TimecardCostCodeDefaulting { get; set; }
        public string ShowPrevailWageRate { get; set; }
        public string CheckShowEmplrNameAddr { get; set; }
        public string CheckEmplrNameAddrLocation { get; set; }
        public string DefaultSeq401k { get; set; }
        public string RequireEmpSutaState { get; set; }
        public string DefaultEmpSutaState { get; set; }
        public string EnableFutaRateOverride { get; set; }
        public string DefaultLocalTaxAgencyNo { get; set; }
        public string CheckFont { get; set; }
        public string DefaultLocalTaxAgencyId { get; set; }
        public string ComputePayrollByUser { get; set; }
        public string CompanyImagePath { get; set; }
        public string SignatureImagePath { get; set; }
        public string OptimizeComputeUnions { get; set; }
        public string Show401kMatchOnStub { get; set; }
        public string AllowPayPeriodOnFutaSutaReports { get; set; }
        public string StubCustom2SignatureAllowed { get; set; }
        public string W2AllowFormUse { get; set; }
        public string PayPeriodDateChangeWhenUnpostedTc { get; set; }
        public string PayCorrectDeductionNo { get; set; }
        public string HourssyncAutosave { get; set; }
        public int PostPlusDays { get; set; }
        public string VoidMethod { get; set; }
        public string PayCorrectDeductionId { get; set; }
        public string ShowExtRateStub { get; set; }
        public string ShowSalProHrsOnStub { get; set; }
        public string AllowMultiplePayPeriods { get; set; }
        public int MaintainTcBackups { get; set; }
        public string AllowRecurringTimecards { get; set; }
        public string PrintEmpAddress { get; set; }
        public string ShowEmpUnionStub { get; set; }
        public string ShowEmpTradeStub { get; set; }
        public string PayRateHoursCol { get; set; }
        public string FringesBenefitsCol { get; set; }
        public string AccrualsCol { get; set; }
        public string BirthdayFlag { get; set; }
        public decimal BirthdayMinAge { get; set; }
        public string AllowChkDatesUnemp { get; set; }
        public string UseFactorEcLcpTrk { get; set; }
        public string PrintDollarSign { get; set; }
        public string EnableEprlive { get; set; }
        public string VerifyTimeInUse { get; set; }
        public string ShowEmployeeSsnSex { get; set; }
        public string RequireSsNoFlag { get; set; }
        public string RoundOtRate { get; set; }
        public string UseAltPrAddress { get; set; }
        public string AltCoName { get; set; }
        public string AltCoAddress1 { get; set; }
        public string AltCoAddress2 { get; set; }
        public string AltCoCity { get; set; }
        public string AltCoState { get; set; }
        public string AltCoZipCode { get; set; }
        public string AltCoPhoneVoice { get; set; }
        public string SelfInsuredCoverage { get; set; }
        public string DtEarnTypeNo { get; set; }
        public decimal DtDayLimit { get; set; }
        public string SatAllOt { get; set; }
        public decimal SatDtAfter { get; set; }
        public string SunAllDt { get; set; }
        public string EnableJobBasedOt { get; set; }
        public string JobIncludeInDailyOt { get; set; }
        public string JobApplyWeeklyOtFirst { get; set; }
        public string TopCheck { get; set; }
        public string CombineEarnCodesOnStub { get; set; }
        public string DtEarnTypeId { get; set; }
        public string UseFactorEcFrgRed { get; set; }
    }
}
