using System;
using System.Collections.Generic;

namespace FSI.ClientMgmtTool.Backend.Foundation.DatabaseContext.Entities
{
    public partial class HisTimecard
    {
        public int CompanyNo { get; set; }
        public int TimecardXref { get; set; }
        public int SequenceNo { get; set; }
        public string EmployeeNo { get; set; }
        public string JobNo { get; set; }
        public DateTime? Dated { get; set; }
        public string PhaseNo { get; set; }
        public string CostCodeNo { get; set; }
        public decimal? Hours { get; set; }
        public decimal? Amount { get; set; }
        public string EarnTypeNo { get; set; }
        public decimal? PayRate { get; set; }
        public string TradeNo { get; set; }
        public string UnionNo { get; set; }
        public decimal? GlExpense { get; set; }
        public decimal? GlPayable { get; set; }
        public decimal? GlBurdenExpense { get; set; }
        public string State { get; set; }
        public string CountyNo { get; set; }
        public string DeptNo { get; set; }
        public string SutaState { get; set; }
        public string PayCode { get; set; }
        public decimal? GlEquipExpense { get; set; }
        public decimal? GlEquipCredit { get; set; }
        public string CountyPrNo { get; set; }
        public string TimecardType { get; set; }
        public string CrewNo { get; set; }
        public string EquipmentNo { get; set; }
        public decimal? EquipmentBillRate { get; set; }
        public string EquipmentOwnership { get; set; }
        public string EquipmentUsageType { get; set; }
        public int? PayWeekNo { get; set; }
        public string UserNo { get; set; }
        public string ShiftNo { get; set; }
        public string RecordStatus { get; set; }
        public string RowModifiedBy { get; set; }
        public DateTime? RowModifiedOn { get; set; }
        public int RowUniqueId { get; set; }
        public int? DesignType { get; set; }
        public string PayPeriodNo { get; set; }
        public string CostClassNo { get; set; }
        public string TaxPrNo { get; set; }
        public string CostCodeCert { get; set; }
        public decimal? DivLevel1 { get; set; }
        public decimal? DivLevel2 { get; set; }
        public decimal? DivLevel3 { get; set; }
        public decimal? DivLevel4 { get; set; }
        public string EquipUnitType { get; set; }
        public int? TransactionNo { get; set; }
        public int? LineNo { get; set; }
        public decimal JcQuantity { get; set; }
        public string CompanyId { get; set; }
        public string CostClassId { get; set; }
        public string CostCodeId { get; set; }
        public string CountyId { get; set; }
        public string CountyPrId { get; set; }
        public string CrewId { get; set; }
        public string DeptId { get; set; }
        public string EarnTypeId { get; set; }
        public string EmployeeId { get; set; }
        public string EquipmentId { get; set; }
        public string JobId { get; set; }
        public string LineId { get; set; }
        public string PayPeriodId { get; set; }
        public string PayWeekId { get; set; }
        public string PhaseId { get; set; }
        public string SequenceId { get; set; }
        public string ShiftId { get; set; }
        public string TaxPrId { get; set; }
        public string TradeId { get; set; }
        public string TransactionId { get; set; }
        public string UnionId { get; set; }
        public string UserId { get; set; }
        public string EqWoNo { get; set; }
        public string ServiceCodeNo { get; set; }
        public string EqWoId { get; set; }
        public string ServiceCodeId { get; set; }
        public string TmGathered { get; set; }
        public string TmWorksheetNo { get; set; }
        public string TmMarkupCategory { get; set; }
        public int? TmMarkupLine { get; set; }
        public int? TmInvRowUniqueId { get; set; }
        public string TmWorksheetId { get; set; }
        public string Description { get; set; }
        public DateTime? CheckDate { get; set; }
        public DateTime? DeliveryTime { get; set; }
        public string DeliveryTimeType { get; set; }
        public DateTime? DeliveryTimeMilitary { get; set; }
        public DateTime? EndTime { get; set; }
        public string EndTimeType { get; set; }
        public DateTime? EndTimeMilitary { get; set; }
        public string PaymentGroupNo { get; set; }
        public decimal RateDifference { get; set; }
        public int GroupRow { get; set; }
        public DateTime? OriginalPayPeriodStartDate { get; set; }
        public DateTime? OriginalPayPeriodEndDate { get; set; }
        public int? VoidTimecardXref { get; set; }
        public string Source { get; set; }
        public string TcRecurTypeNo { get; set; }
        public string OtRateRounded { get; set; }
        public string UserChgRounded { get; set; }
        public int? AuditNumber { get; set; }

        public CostCodes Co { get; set; }
        public Employees Employees { get; set; }
        public Jobs Jobs { get; set; }
    }
}
